# Site settings
title: Öko-Hungary
email: info@oko.eu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/oko/" # the subpath of your site, e.g. /blog/
url: "https://vestalux.github.io" # the base hostname & protocol for your site

facebook_username: Öko-Hungary-1802766113351259
github_username:

# Build settings
markdown: kramdown

collections:
  portfolio:
    output: true
    permalink: portfolio/:title/
