# Site settings
title: Öko-Hungary
email: hi@oko-hungary.eu
phone: +36-70-977-4755
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oko-hungary.eu" # the base hostname & protocol for your site

facebook_username: okohungary
github_username:
logo: "img/logo.svg"
ga: UA-17340317-11
# Build settings
markdown: kramdown

collections:
  portfolio:
    output: true
    permalink: portfolio/:title/
